local ADDON_NAME, OneWoW = ...

local function L(key) return OneWoW.L and OneWoW.L[key] or key end

OneWoW.SearchData = {

    -- OneWoW Core: Settings
    {
        path     = function() return L("SRCH_PATH_OW_SETTINGS") end,
        desc     = function() return L("SRCH_DESC_OW_SETTINGS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "settings", subtab = "settings",
        keywords = {"settings", "options", "config", "configure", "preferences", "general"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_SETTINGS_LANGUAGE") end,
        desc     = function() return L("SRCH_DESC_OW_SETTINGS_LANGUAGE") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "settings", subtab = "settings",
        keywords = {"language", "locale", "translation", "spanish", "korean", "french", "russian", "german", "english"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_SETTINGS_THEME") end,
        desc     = function() return L("SRCH_DESC_OW_SETTINGS_THEME") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "settings", subtab = "settings",
        keywords = {"theme", "color", "colour", "appearance", "dark mode", "light mode", "skin", "dark", "light", "green", "blue", "purple", "gold", "red", "orange", "teal"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_SETTINGS_MINIMAP") end,
        desc     = function() return L("SRCH_DESC_OW_SETTINGS_MINIMAP") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "settings", subtab = "settings",
        keywords = {"minimap", "icon", "button", "hide minimap", "show minimap", "horde", "alliance", "neutral", "faction"},
    },

    -- OneWoW Core: Tooltips
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"tooltip", "tooltips", "hover", "item info", "disable tooltips", "turn off tooltips", "enable tooltips"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS_ITEMTYPES") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS_ITEMTYPES") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"item type", "item types", "consumable", "reagent", "gear type", "category tooltip"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS_TECHIDS") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS_TECHIDS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"item id", "spell id", "npc id", "technical id", "ids", "debug tooltip", "itemid", "spellid", "quest id", "currency id", "mount id", "pet id", "species id", "enchant id", "icon id", "expansion id", "set id", "decor entry id", "recipe id", "equipment set id", "essence id", "conduit id", "outfit id", "macro id", "object id", "ability id", "area poi id", "artifact power id", "bonus id", "companion id", "criteria id", "gem id", "source id", "talent id", "trait definition id", "trait entry id", "trait node id", "vignette id", "visual id", "bonusid", "gemid", "talentid", "traitid", "vignetteid", "questid", "currencyid", "mountid"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS_CUSTNOTES") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS_CUSTNOTES") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"custom notes", "player notes", "npc notes", "item notes", "note tooltip", "my notes"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS_RECIPE") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS_RECIPE") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"recipe", "recipe knowledge", "crafting tooltip", "known by", "who knows", "profession recipe"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS_COLLECT") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS_COLLECT") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"collections", "mount tooltip", "pet tooltip", "toy tooltip", "collected", "already have", "collection status"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS_ITEMTRACK") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS_ITEMTRACK") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"item tracker", "item count", "how many", "character count", "item quantity", "all characters"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS_NOTEWARN") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS_NOTEWARN") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"note warning", "warning", "flagged note", "alert note", "tooltip warning"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS_ITEMSTATUS") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS_ITEMSTATUS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"item status", "soulbound", "warbound", "bind on equip", "boe", "bop", "bou", "bound status"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS_PETS") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS_PETS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"pet tooltip", "caged pet", "battle pet tooltip", "pet info", "pet collection", "pet source", "caged pet tooltip", "species"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOOLTIPS_VALUE") end,
        desc     = function() return L("SRCH_DESC_OW_TOOLTIPS_VALUE") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "tooltips",
        keywords = {"value", "item value", "vendor price", "vendor sell", "vendor cost", "ah price", "auction price", "gold value", "sell price", "buy price", "coin", "money"},
    },

    -- OneWoW Core: Overlays
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"overlay", "overlays", "bag overlay", "bag icon", "item overlay", "bag slot", "icon overlay"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_CONSUMABLES") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_CONSUMABLES") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"consumable", "consumables", "potion", "food", "flask", "overlay consumable"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_JUNK") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_JUNK") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"junk", "grey", "gray", "vendor junk", "sell junk", "overlay junk"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_MOUNTS") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_MOUNTS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"mount", "mounts", "mount item", "overlay mount"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_PETS") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_PETS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"pet", "pets", "battle pet", "caged pet", "companion pet", "overlay pet"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_QUEST") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_QUEST") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"quest item", "quest items", "quest", "overlay quest"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_REAGENTS") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_REAGENTS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"reagent", "reagents", "crafting material", "material", "overlay reagent"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_TOYS") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_TOYS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"toy", "toys", "overlay toy"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_UPGRADES") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_UPGRADES") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"upgrade", "upgrades", "gear upgrade", "is upgrade", "overlay upgrade"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_KNOWN") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_KNOWN") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"known", "already known", "learned", "already have", "overlay known"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_SOULBOUND") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_SOULBOUND") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"soulbound", "bound to you", "overlay soulbound", "bop"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_WARBOUND") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_WARBOUND") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"warbound", "overlay warbound", "bou", "warbound until equipped"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_ICONSTYLE") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_ICONSTYLE") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"overlay icon", "icon style", "overlay position", "icon position", "custom icon"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_HOUSING") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_HOUSING") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"housing", "housing decor", "decoration", "house", "decor overlay"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_ITEMLEVEL") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_ITEMLEVEL") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"item level", "ilvl", "ilevel", "item level overlay", "show ilvl", "pet level", "container slots", "bag slots"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_PROTECTED") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_PROTECTED") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"protected", "protect item", "lock item", "protected overlay"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_UNKNOWN") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_UNKNOWN") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"unknown items", "unknown", "unidentified", "other items", "unknown overlay"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_RECIPES") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_RECIPES") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"recipe overlay", "learnable recipe", "recipe item"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_BAGANATOR") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_BAGANATOR") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"baganator", "bagon", "baganator integration", "baganator overlay", "baganator bags"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_BAGNON") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_BAGNON") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"bagnon", "bagnon integration", "bagnon overlay", "bagnon bags"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_ARKINV") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_ARKINV") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"arkinventory", "ark inventory", "ark", "arkinventory integration", "arkinventory overlay"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_OVERLAYS_BETTERBAGS") end,
        desc     = function() return L("SRCH_DESC_OW_OVERLAYS_BETTERBAGS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "overlays",
        keywords = {"better bags", "betterbags", "betterbags integration", "betterbags overlay", "betterbags bags"},
    },

    -- OneWoW Core: Toast Alerts
    {
        path     = function() return L("SRCH_PATH_OW_TOAST") end,
        desc     = function() return L("SRCH_DESC_OW_TOAST") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "toastalerts",
        keywords = {"toast", "toast alert", "toast alerts", "popup", "pop-up", "notification", "alert", "notify"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOAST_SOUND") end,
        desc     = function() return L("SRCH_DESC_OW_TOAST_SOUND") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "toastalerts",
        keywords = {"toast sound", "alert sound", "notification sound", "chime", "raid alert sound"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOAST_LOOT") end,
        desc     = function() return L("SRCH_DESC_OW_TOAST_LOOT") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "toastalerts",
        keywords = {"loot toast", "loot notification", "loot alert", "loot popup"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOAST_NOTES") end,
        desc     = function() return L("SRCH_DESC_OW_TOAST_NOTES") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "toastalerts",
        keywords = {"note toast", "note alert", "note popup", "noted player", "noted npc"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOAST_INSTANCES") end,
        desc     = function() return L("SRCH_DESC_OW_TOAST_INSTANCES") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "toastalerts",
        keywords = {"instance toast", "dungeon notification", "raid notification", "entering instance"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_TOAST_RECIPES_PROF") end,
        desc     = function() return L("SRCH_DESC_OW_TOAST_RECIPES_PROF") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "toastalerts",
        keywords = {
            "recipe toast", "recipe alert", "recipe notification", "recipes toast",
            "profession toast", "professions toast", "my profession", "my professions",
            "only my professions", "trade skill toast", "tradeskill toast", "crafting toast",
            "recipe professions", "collection detection",
        },
    },

    -- OneWoW Core: Portals
    {
        path     = function() return L("SRCH_PATH_OW_PORTALS") end,
        desc     = function() return L("SRCH_DESC_OW_PORTALS") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "portals",
        keywords = {"portal", "portals", "portal hub", "hearthstone", "teleport", "travel", "esc menu portal"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_PORTALS_ESC") end,
        desc     = function() return L("SRCH_DESC_OW_PORTALS_ESC") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "portals",
        keywords = {"portal esc", "esc portal", "game menu portal", "escape menu", "portal menu"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_PORTALS_RANDOM") end,
        desc     = function() return L("SRCH_DESC_OW_PORTALS_RANDOM") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "portals",
        keywords = {"random hearthstone", "hearthstone random", "random hearth", "hearthstone collection"},
    },
    {
        path     = function() return L("SRCH_PATH_OW_PORTALS_DISPLAY") end,
        desc     = function() return L("SRCH_DESC_OW_PORTALS_DISPLAY") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "qol", subtab = "portals",
        keywords = {"portal display", "show portals", "seasonal portals", "portal options", "which portals"},
    },

    -- OneWoW Home
    {
        path     = function() return L("SRCH_PATH_OW_HOME") end,
        desc     = function() return L("SRCH_DESC_OW_HOME") end,
        addonKey = nil, addonLabel = "OneWoW",
        navType = "module", module = "home", subtab = nil,
        keywords = {"home", "dashboard", "status", "addon status", "installed addons", "enabled"},
    },

    -- AltTracker
    {
        path     = function() return L("SRCH_PATH_AT_SUMMARY") end,
        desc     = function() return L("SRCH_DESC_AT_SUMMARY") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "summary",
        keywords = {"summary", "overview", "account overview", "all characters", "dashboard", "alttracker", "alts"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_PROGRESS") end,
        desc     = function() return L("SRCH_DESC_AT_PROGRESS") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "progress",
        keywords = {"progress", "dungeon progress", "raid progress", "season", "weekly reset", "completion", "mythic"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_PROGRESS_MYTHIC") end,
        desc     = function() return L("SRCH_DESC_AT_PROGRESS_MYTHIC") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "progress",
        keywords = {"mythic plus", "mythic+", "m+", "rating", "dungeon rating", "keystone"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_PROGRESS_RAIDS") end,
        desc     = function() return L("SRCH_DESC_AT_PROGRESS_RAIDS") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "progress",
        keywords = {"raids", "lfr", "normal raid", "heroic raid", "mythic raid", "raid completion", "raid progress"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_BANK") end,
        desc     = function() return L("SRCH_DESC_AT_BANK") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "bank",
        keywords = {"bank", "storage", "bank items", "reagent bank", "warband vault", "vault", "character bank"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_BANK_WARBAND") end,
        desc     = function() return L("SRCH_DESC_AT_BANK_WARBAND") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "bank",
        keywords = {"warband bank", "shared bank", "account bank", "warband vault", "warband storage"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_BANK_GUILD") end,
        desc     = function() return L("SRCH_DESC_AT_BANK_GUILD") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "bank",
        keywords = {"guild bank", "guild storage", "guild vault", "guild items"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_EQUIPMENT") end,
        desc     = function() return L("SRCH_DESC_AT_EQUIPMENT") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "equipment",
        keywords = {"equipment", "gear", "ilvl", "item level", "equipped", "equipment set", "armor"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_PROFESSIONS") end,
        desc     = function() return L("SRCH_DESC_AT_PROFESSIONS") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "professions",
        keywords = {"professions", "profession", "skill level", "crafting", "recipes", "profession cooldown", "daily cooldown"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_PROFESSIONS_CD") end,
        desc     = function() return L("SRCH_DESC_AT_PROFESSIONS_CD") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "professions",
        keywords = {"profession cooldown", "daily cooldown", "craft cooldown", "cooldown ready", "cooldown tracker"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_AUCTIONS") end,
        desc     = function() return L("SRCH_DESC_AT_AUCTIONS") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "auctions",
        keywords = {"auctions", "auction house", "ah", "posted auctions", "sold items", "auction history"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_FINANCIALS") end,
        desc     = function() return L("SRCH_DESC_AT_FINANCIALS") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "financials",
        keywords = {"financials", "gold", "income", "expense", "money", "gold tracking", "transaction history", "profit", "loss"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_FINANCIALS_TRANS") end,
        desc     = function() return L("SRCH_DESC_AT_FINANCIALS_TRANS") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "financials",
        keywords = {"transactions", "transaction log", "gold log", "spending log", "income log"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_FINANCIALS_WARBAND") end,
        desc     = function() return L("SRCH_DESC_AT_FINANCIALS_WARBAND") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "financials",
        keywords = {"warband transfer", "bank transfer", "gold transfer", "warband gold", "transfer gold"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_ITEMS") end,
        desc     = function() return L("SRCH_DESC_AT_ITEMS") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "items",
        keywords = {"items", "item search", "find item", "where is", "inventory search", "item location"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_LOCKOUTS") end,
        desc     = function() return L("SRCH_DESC_AT_LOCKOUTS") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "lockouts",
        keywords = {"lockouts", "lockout", "raid lockout", "dungeon lockout", "weekly lockout", "reset", "tuesday reset", "instance lockout"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_PROFILES") end,
        desc     = function() return L("SRCH_DESC_AT_PROFILES") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "profiles",
        keywords = {"profiles", "profile", "save settings", "load settings", "character profile"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_SETTINGS") end,
        desc     = function() return L("SRCH_DESC_AT_SETTINGS") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "settings", subtab = "alttracker",
        keywords = {"alttracker settings", "tracker settings", "tracking options", "configure alttracker"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_SUMMARY_CHARINFO") end,
        desc     = function() return L("SRCH_DESC_AT_SUMMARY_CHARINFO") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "summary",
        keywords = {"character info", "character level", "class", "spec", "specialization", "race", "location"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_SUMMARY_GOLD") end,
        desc     = function() return L("SRCH_DESC_AT_SUMMARY_GOLD") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "summary",
        keywords = {"gold", "total gold", "gold per character", "money", "wealth", "gold summary"},
    },
    {
        path     = function() return L("SRCH_PATH_AT_SUMMARY_PLAYTIME") end,
        desc     = function() return L("SRCH_DESC_AT_SUMMARY_PLAYTIME") end,
        addonKey = "OneWoW_AltTracker", addonLabel = "AltTracker",
        navType = "module", module = "alttracker", subtab = "summary",
        keywords = {"play time", "time played", "hours played", "playtime"},
    },

    -- QoL
    {
        path     = function() return L("SRCH_PATH_QOL_FEATURES") end,
        desc     = function() return L("SRCH_DESC_QOL_FEATURES") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"qol", "quality of life", "features", "modules", "qol features"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_AFKPANEL") end,
        desc     = function() return L("SRCH_DESC_QOL_AFKPANEL") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"afk", "afk panel", "away from keyboard", "idle screen"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_AUTODELETE") end,
        desc     = function() return L("SRCH_DESC_QOL_AUTODELETE") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"auto delete", "autodelete", "junk delete", "delete junk", "grey items", "gray items", "automatic delete"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_AUTOMOUNT") end,
        desc     = function() return L("SRCH_DESC_QOL_AUTOMOUNT") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"auto mount", "automount", "mount automatically", "auto ride", "automatic mount"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_AUTOOPEN") end,
        desc     = function() return L("SRCH_DESC_QOL_AUTOOPEN") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"auto open", "autoopen", "open containers", "open bags", "automatic open", "open boxes"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_AUTOREPAIR") end,
        desc     = function() return L("SRCH_DESC_QOL_AUTOREPAIR") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"auto repair", "autorepair", "repair gear", "durability", "automatic repair", "repair vendor"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_BAGBAR") end,
        desc     = function() return L("SRCH_DESC_QOL_BAGBAR") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"bag bar", "bagbar", "bag slots", "free slots", "inventory bar", "bags bar"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_CHARINFO") end,
        desc     = function() return L("SRCH_DESC_QOL_CHARINFO") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"charinfo", "character info", "character stats", "char info", "enhanced character"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_COORDS") end,
        desc     = function() return L("SRCH_DESC_QOL_COORDS") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"coordinates", "coords", "location", "x y", "map position", "coordinates display"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_COPYTEXT") end,
        desc     = function() return L("SRCH_DESC_QOL_COPYTEXT") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"copy text", "copytext", "copy chat", "clipboard", "copy link", "text copy"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_CURSOR") end,
        desc     = function() return L("SRCH_DESC_QOL_CURSOR") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"cursor", "cursor enhancer", "cursor glow", "cursor highlight", "cursor visibility", "mouse cursor"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_FASTFWD") end,
        desc     = function() return L("SRCH_DESC_QOL_FASTFWD") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"fast forward", "fastforward", "skip cinematic", "skip animation", "speed up", "cinematic skip"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_FASTLOOT") end,
        desc     = function() return L("SRCH_DESC_QOL_FASTLOOT") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"fast loot", "fastloot", "auto loot", "autoloot", "automatic loot", "loot all"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_PLAYMOUNTS") end,
        desc     = function() return L("SRCH_DESC_QOL_PLAYMOUNTS") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"play mounts", "playmounts", "mount emote", "mount interact", "pet mount"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_PROFPANEL") end,
        desc     = function() return L("SRCH_DESC_QOL_PROFPANEL") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"professions panel", "profession panel", "quick profession", "open profession", "craft panel"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_QUESTTOOLS") end,
        desc     = function() return L("SRCH_DESC_QOL_QUESTTOOLS") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"quest tools", "questtools", "quest helper", "auto accept quest", "auto complete quest", "quest ui"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_VENDORPANEL") end,
        desc     = function() return L("SRCH_DESC_QOL_VENDORPANEL") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"vendor panel", "vendorpanel", "vendor filter", "vendor sort", "sell items", "vendor window", "vendor ui"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_ESCPANEL") end,
        desc     = function() return L("SRCH_DESC_QOL_ESCPANEL") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"esc panel", "escpanel", "escape menu", "tasks", "notes panel", "alerts", "game menu"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_QUESTITEMBAR") end,
        desc     = function() return L("SRCH_DESC_QOL_QUESTITEMBAR") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "features",
        keywords = {"quest item bar", "questitembar", "quest bar", "quest items", "item bar", "quest tracking"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_TOGGLES") end,
        desc     = function() return L("SRCH_DESC_QOL_TOGGLES") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "toggles",
        keywords = {"toggles", "cvar", "cvars", "console variable", "console variables", "variables", "game settings", "wow settings", "interface options", "settings panel", "toggle settings"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_TOGGLES_GAMEPLAY") end,
        desc     = function() return L("SRCH_DESC_QOL_TOGGLES_GAMEPLAY") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "toggles",
        keywords = {"gameplay", "auto loot", "autoloot", "self cast", "dismount", "auto dismount", "interact", "auto stand", "auto unshift", "assist attack", "keydown", "deselect"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_TOGGLES_INTERFACE") end,
        desc     = function() return L("SRCH_DESC_QOL_TOGGLES_INTERFACE") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "toggles",
        keywords = {"interface", "action bar", "action bars", "cooldown countdown", "buff duration", "ui scale", "target of target", "target castbar", "minimap rotate", "compare items"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_TOGGLES_NAMEPLATES") end,
        desc     = function() return L("SRCH_DESC_QOL_TOGGLES_NAMEPLATES") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "toggles",
        keywords = {"nameplates", "nameplate", "enemy nameplates", "friendly nameplates", "nameplate scale", "nameplate distance", "class color nameplate", "personal nameplate"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_TOGGLES_COMBATTEXT") end,
        desc     = function() return L("SRCH_DESC_QOL_TOGGLES_COMBATTEXT") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "toggles",
        keywords = {"combat text", "floating combat text", "damage numbers", "healing numbers", "fct", "honor gains", "combo points", "energy gains"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_TOGGLES_CAMERA") end,
        desc     = function() return L("SRCH_DESC_QOL_TOGGLES_CAMERA") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "toggles",
        keywords = {"camera", "camera zoom", "zoom distance", "camera bobbing", "camera speed", "dynamic pitch", "water collision", "camera yaw", "camera pitch"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_TOGGLES_CHAT") end,
        desc     = function() return L("SRCH_DESC_QOL_TOGGLES_CHAT") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "toggles",
        keywords = {"chat", "chat bubbles", "chat style", "color chat names", "block trades", "block channel invites", "profanity filter", "chat scroll", "guild notify"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_TOGGLES_AUDIO") end,
        desc     = function() return L("SRCH_DESC_QOL_TOGGLES_AUDIO") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "toggles",
        keywords = {"audio", "sound", "volume", "music", "sound effects", "sfx", "dialog", "ambience", "pet sounds", "footsteps", "mute", "master volume"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_TOGGLES_GRAPHICS") end,
        desc     = function() return L("SRCH_DESC_QOL_TOGGLES_GRAPHICS") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "toggles",
        keywords = {"graphics", "fps", "fps cap", "max fps", "vsync", "render scale", "particles", "anti aliasing", "graphics quality", "triple buffer", "colorblind", "low health warning"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_TOGGLES_NETWORK") end,
        desc     = function() return L("SRCH_DESC_QOL_TOGGLES_NETWORK") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "qol", subtab = "toggles",
        keywords = {"network", "lag", "latency", "spell queue", "spell queue window", "nagle", "reduced lag", "fix lag", "network optimization"},
    },
    {
        path     = function() return L("SRCH_PATH_QOL_SETTINGS") end,
        desc     = function() return L("SRCH_DESC_QOL_SETTINGS") end,
        addonKey = "OneWoW_QoL", addonLabel = "OneWoW QoL",
        navType = "module", module = "settings", subtab = "qol",
        keywords = {"qol settings", "qol options", "configure qol"},
    },

    -- Notes
    {
        path     = function() return L("SRCH_PATH_NOTES_NOTES") end,
        desc     = function() return L("SRCH_DESC_NOTES_NOTES") end,
        addonKey = "OneWoW_Notes", addonLabel = "Notes",
        navType = "module", module = "notes", subtab = "notes",
        keywords = {"notes", "note", "create note", "write note", "my notes", "note list"},
    },
    {
        path     = function() return L("SRCH_PATH_NOTES_PLAYERS") end,
        desc     = function() return L("SRCH_DESC_NOTES_PLAYERS") end,
        addonKey = "OneWoW_Notes", addonLabel = "Notes",
        navType = "module", module = "notes", subtab = "players",
        keywords = {"player notes", "notes players", "player info", "player lookup", "player contact"},
    },
    {
        path     = function() return L("SRCH_PATH_NOTES_NPCS") end,
        desc     = function() return L("SRCH_DESC_NOTES_NPCS") end,
        addonKey = "OneWoW_Notes", addonLabel = "Notes",
        navType = "module", module = "notes", subtab = "npcs",
        keywords = {"npc notes", "notes npc", "npc info", "vendor note", "merchant note", "npc lookup"},
    },
    {
        path     = function() return L("SRCH_PATH_NOTES_ZONES") end,
        desc     = function() return L("SRCH_DESC_NOTES_ZONES") end,
        addonKey = "OneWoW_Notes", addonLabel = "Notes",
        navType = "module", module = "notes", subtab = "zones",
        keywords = {"zone notes", "notes zones", "location notes", "map notes", "area notes", "zone"},
    },
    {
        path     = function() return L("SRCH_PATH_NOTES_ITEMS") end,
        desc     = function() return L("SRCH_DESC_NOTES_ITEMS") end,
        addonKey = "OneWoW_Notes", addonLabel = "Notes",
        navType = "module", module = "notes", subtab = "items",
        keywords = {"item notes", "notes items", "item annotation", "item label"},
    },
    {
        path     = function() return L("SRCH_PATH_NOTES_SETTINGS") end,
        desc     = function() return L("SRCH_DESC_NOTES_SETTINGS") end,
        addonKey = "OneWoW_Notes", addonLabel = "Notes",
        navType = "module", module = "settings", subtab = "notes",
        keywords = {"notes settings", "note options", "configure notes"},
    },

    -- Catalog
    {
        path     = function() return L("SRCH_PATH_CAT_JOURNAL") end,
        desc     = function() return L("SRCH_DESC_CAT_JOURNAL") end,
        addonKey = "OneWoW_Catalog", addonLabel = "Catalog",
        navType = "module", module = "catalog", subtab = "journal",
        keywords = {"journal", "dungeon journal", "raid journal", "boss list", "boss drops", "instance journal"},
    },
    {
        path     = function() return L("SRCH_PATH_CAT_JOURNAL_DUNGEONS") end,
        desc     = function() return L("SRCH_DESC_CAT_JOURNAL_DUNGEONS") end,
        addonKey = "OneWoW_Catalog", addonLabel = "Catalog",
        navType = "module", module = "catalog", subtab = "journal",
        keywords = {"dungeons", "dungeon list", "dungeon bosses", "dungeon drops", "dungeon loot"},
    },
    {
        path     = function() return L("SRCH_PATH_CAT_JOURNAL_RAIDS") end,
        desc     = function() return L("SRCH_DESC_CAT_JOURNAL_RAIDS") end,
        addonKey = "OneWoW_Catalog", addonLabel = "Catalog",
        navType = "module", module = "catalog", subtab = "journal",
        keywords = {"raids", "raid list", "raid bosses", "raid drops", "raid loot", "raid journal"},
    },
    {
        path     = function() return L("SRCH_PATH_CAT_VENDORS") end,
        desc     = function() return L("SRCH_DESC_CAT_VENDORS") end,
        addonKey = "OneWoW_Catalog", addonLabel = "Catalog",
        navType = "module", module = "catalog", subtab = "vendors",
        keywords = {"vendor", "vendors", "npc vendor", "merchant", "sell", "buy", "shop", "vendor location", "where to buy"},
    },
    {
        path     = function() return L("SRCH_PATH_CAT_VENDORS_FIND") end,
        desc     = function() return L("SRCH_DESC_CAT_VENDORS_FIND") end,
        addonKey = "OneWoW_Catalog", addonLabel = "Catalog",
        navType = "module", module = "catalog", subtab = "vendors",
        keywords = {"find vendor", "vendor search", "vendor npc", "npc location", "vendor map"},
    },
    {
        path     = function() return L("SRCH_PATH_CAT_TRADESKILLS") end,
        desc     = function() return L("SRCH_DESC_CAT_TRADESKILLS") end,
        addonKey = "OneWoW_Catalog", addonLabel = "Catalog",
        navType = "module", module = "catalog", subtab = "tradeskills",
        keywords = {"tradeskills", "tradeskill", "recipes", "recipe list", "crafting recipes", "profession recipes", "materials", "reagents needed"},
    },
    {
        path     = function() return L("SRCH_PATH_CAT_TRADESKILLS_RECIPE") end,
        desc     = function() return L("SRCH_DESC_CAT_TRADESKILLS_RECIPE") end,
        addonKey = "OneWoW_Catalog", addonLabel = "Catalog",
        navType = "module", module = "catalog", subtab = "tradeskills",
        keywords = {"recipe search", "find recipe", "search recipe", "craft search", "recipe name"},
    },
    {
        path     = function() return L("SRCH_PATH_CAT_ITEMSEARCH") end,
        desc     = function() return L("SRCH_DESC_CAT_ITEMSEARCH") end,
        addonKey = "OneWoW_Catalog", addonLabel = "Catalog",
        navType = "module", module = "catalog", subtab = "itemsearch",
        keywords = {"item search", "search items", "find item", "item database", "item lookup", "item catalog"},
    },
    {
        path     = function() return L("SRCH_PATH_CAT_SETTINGS") end,
        desc     = function() return L("SRCH_DESC_CAT_SETTINGS") end,
        addonKey = "OneWoW_Catalog", addonLabel = "Catalog",
        navType = "module", module = "settings", subtab = "catalog",
        keywords = {"catalog settings", "catalog options", "configure catalog"},
    },

    -- DirectDeposit
    {
        path    = function() return L("SRCH_PATH_DD") end,
        desc    = function() return L("SRCH_DESC_DD") end,
        addonKey = "OneWoW_DirectDeposit", addonLabel = "DirectDeposit",
        navType = "external",
        navFunc = function()
            if _G.OneWoW_DirectDeposit and _G.OneWoW_DirectDeposit.GUI then
                _G.OneWoW_DirectDeposit.GUI:Toggle()
            end
        end,
        keywords = {"deposit", "direct deposit", "directdeposit", "bank deposit", "item deposit", "deposit items"},
    },
    {
        path    = function() return L("SRCH_PATH_DD_DEPOSIT") end,
        desc    = function() return L("SRCH_DESC_DD_DEPOSIT") end,
        addonKey = "OneWoW_DirectDeposit", addonLabel = "DirectDeposit",
        navType = "external",
        navFunc = function()
            if _G.OneWoW_DirectDeposit and _G.OneWoW_DirectDeposit.GUI then
                _G.OneWoW_DirectDeposit.GUI:Toggle()
            end
        end,
        keywords = {"item deposit", "send to bank", "deposit bag", "bank items", "move to bank"},
    },
    {
        path    = function() return L("SRCH_PATH_DD_SETTINGS") end,
        desc    = function() return L("SRCH_DESC_DD_SETTINGS") end,
        addonKey = "OneWoW_DirectDeposit", addonLabel = "DirectDeposit",
        navType = "external",
        navFunc = function()
            if _G.OneWoW_DirectDeposit and _G.OneWoW_DirectDeposit.GUI then
                _G.OneWoW_DirectDeposit.GUI:Toggle()
            end
        end,
        keywords = {"directdeposit settings", "deposit settings", "deposit options"},
    },

    -- ShoppingList
    {
        path    = function() return L("SRCH_PATH_SL") end,
        desc    = function() return L("SRCH_DESC_SL") end,
        addonKey = "OneWoW_ShoppingList", addonLabel = "Shopping List",
        navType = "external",
        navFunc = function()
            if _G.OneWoW_ShoppingList and _G.OneWoW_ShoppingList.MainWindow then
                _G.OneWoW_ShoppingList.MainWindow:Toggle()
            end
        end,
        keywords = {"shopping list", "shopping", "buy list", "need to buy", "item list", "wishlist"},
    },
    {
        path    = function() return L("SRCH_PATH_SL_ADD") end,
        desc    = function() return L("SRCH_DESC_SL_ADD") end,
        addonKey = "OneWoW_ShoppingList", addonLabel = "Shopping List",
        navType = "external",
        navFunc = function()
            if _G.OneWoW_ShoppingList and _G.OneWoW_ShoppingList.MainWindow then
                _G.OneWoW_ShoppingList.MainWindow:Toggle()
            end
        end,
        keywords = {"add to list", "add item", "shopping add", "list item", "track item"},
    },
    {
        path    = function() return L("SRCH_PATH_SL_REAGENTS") end,
        desc    = function() return L("SRCH_DESC_SL_REAGENTS") end,
        addonKey = "OneWoW_ShoppingList", addonLabel = "Shopping List",
        navType = "external",
        navFunc = function()
            if _G.OneWoW_ShoppingList and _G.OneWoW_ShoppingList.MainWindow then
                _G.OneWoW_ShoppingList.MainWindow:Toggle()
            end
        end,
        keywords = {"reagents", "profession reagents", "crafting materials", "recipe materials", "shopping reagents"},
    },
    {
        path    = function() return L("SRCH_PATH_SL_OVERLAYS") end,
        desc    = function() return L("SRCH_DESC_SL_OVERLAYS") end,
        addonKey = "OneWoW_ShoppingList", addonLabel = "Shopping List",
        navType = "external",
        navFunc = function()
            if _G.OneWoW_ShoppingList and _G.OneWoW_ShoppingList.MainWindow then
                _G.OneWoW_ShoppingList.MainWindow:Toggle()
            end
        end,
        keywords = {"shopping overlay", "bag highlight", "list highlight", "shopping bag"},
    },
}
